spring.datasource.url=jdbc:postgresql://localhost:5432/doctorapp
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

security.jwt.secret=Q2hhbmdlTWVTZWNyZXRLZXlDaGFuZ2VNZVNlY3JldEtleTEyMzQ1Ng==
security.jwt.expiration=86400000

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=mailtrap
spring.mail.password=secret
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
