export const NATIONALITIES = [
  "Afghane", "Albanaise", "Algérienne", "Allemande", "Américaine", "Andorrane", "Angolaise", "Antiguaise-et-Barbudienne",
  "Argentine", "Arménienne", "Australienne", "Autrichienne", "Azerbaïdjanaise", "Bahamienne", "Bahreïnienne", "Bangladaise",
  "Barbadienne", "Belge", "Bélizienne", "Béninoise", "Bhoutanaise", "Biélorusse", "Birmane", "Bolivienne", "Bosnienne",
  "Botswanaise", "Brésilienne", "Britannique", "Brunéienne", "Bulgare", "Burkinabè", "Burundaise", "Cambodgienne",
  "Camerounaise", "Canadienne", "Cap-verdienne", "Centrafricaine", "Chilienne", "Chinoise", "Chypriote", "Colombienne",
  "Comorienne", "Congolaise (Brazzaville)", "Congolaise (Kinshasa)", "Costaricienne", "Croate", "Cubaine", "Danoise",
  "Djiboutienne", "Dominicaine", "Dominiquaise", "Égyptienne", "Émirienne", "Équatorienne", "Érythréenne", "Espagnole",
  "Estonienne", "Éthiopienne", "Fidjienne", "Finlandaise", "Française", "Gabonaise", "Gambienne", "Géorgienne", "Ghanéenne",
  "Grecque", "Grenadienne", "Guatémaltèque", "Guinéenne", "Guinéenne (Bissau)", "Équato-guinéenne", "Guyanienne",
  "Haïtienne", "Hondurienne", "Hongroise", "Indienne", "Indonésienne", "Irakienne", "Iranienne", "Irlandaise",
  "Islandaise", "Israélienne", "Italienne", "Ivoirienne", "Jamaïcaine", "Japonaise", "Jordanienne", "Kazakhe", "Kényane",
  "Kirghize", "Kiribatienne", "Kosovare", "Koweïtienne", "Laotienne", "Lesothane", "Lettone", "Libanaise", "Libérienne",
  "Libyenne", "Liechtensteinoise", "Lituanienne", "Luxembourgeoise", "Macédonienne", "Malaisienne", "Malawienne",
  "Maldivienne", "Malgache", "Malienne", "Maltaise", "Marocaine", "Marshallaise", "Mauricienne", "Mauritanienne",
  "Mexicaine", "Micronésienne", "Moldave", "Monégasque", "Mongole", "Monténégrine", "Mozambicaine", "Namibienne",
  "Nauruane", "Néerlandaise", "Néo-zélandaise", "Népalaise", "Nicaraguayenne", "Nigériane", "Nigérienne",
  "Nord-coréenne", "Norvégienne", "Omanaise", "Ougandaise", "Ouzbèke", "Pakistanaise", "Palaosienne", "Palestinienne",
  "Panaméenne", "Papouane-Néo-Guinéenne", "Paraguayenne", "Péruvienne", "Philippine", "Polonaise", "Portugaise",
  "Qatarienne", "Roumaine", "Russe", "Rwandaise", "Saint-Lucienne", "Saint-Marinaise", "Saint-Vincentaise",
  "Salomonaise", "Salvadorienne", "Samoane", "Santoméenne", "Saoudienne", "Sénégalaise", "Serbe", "Seychelloise",
  "Sierra-Léonaise", "Singapourienne", "Slovaque", "Slovène", "Somalienne", "Soudanaise", "Sud-Soudanaise",
  "Sri-Lankaise", "Sud-Africaine", "Sud-Coréenne", "Suédoise", "Suisse", "Surinamaise", "Swazie", "Syrienne",
  "Tadjike", "Taïwanaise", "Tanzanienne", "Tchadienne", "Tchèque", "Thaïlandaise", "Timoraise", "Togolaise",
  "Tongienne", "Trinidadienne", "Tunisienne", "Turkmène", "Turque", "Tuvaluane", "Ukrainienne", "Uruguayenne",
  "Vanuatuane", "Vénézuélienne", "Vietnamienne", "Yéménite", "Zambienne", "Zimbabwéenne",
];
